[tools]
bun = "latest"
go = "1.21"
node = "20.19.3"
python = "3.9.21"
zig = "latest"
uv = "latest"
cmake = "latest"
tmux = "latest"
neovim = "latest"
fd = "latest"
ripgrep = "latest"
fzf = "latest"
yazi = "latest"
yarn = "latest"
upx = "latest"
mdbook = "latest"
ninja = "1.12.1"
rust = "latest"
starship = "1.22.1"
# clang-format = "latest"
zoxide = "latest"
lazygit = "latest"
mold = "latest"
tree-sitter = "latest"
eza = "latest"
atuin = "latest"
typst = "latest"
yq = "latest"
usage = "latest"
helix = "latest"
clangd = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

# Simple hostname replacement
url_replacements = {  "https://github.com" = "https://xiu.lzg.cc/gh", "https://gitlab.com" = "https://xiu.lzg.cc/gl" }

# Regex patterns
#url_replacements = {
#  "regex:^http://(.+)" = "https://$1",
#  "regex:https://github\\.com/([^/]+)/([^/]+)/releases/download/(.+)" = 
#    "https://hub.corp.com/artifactory/github/$1/$2/$3"
#}


[settings.python]
uv_venv_auto = true


[settings.aqua]
registry_url = "https://xiu.lzg.cc/gh/aquaproj/aqua-registry"

[settings.node]
mirror_url = "https://npmmirror.com/mirrors/node/"

[settings.pipx]
registry_url = "https://xiu.lzg.cc/pypi/{}/json"
